# These are supported funding model platforms

github: [YOUR_GITHUB_USERNAME]
patreon: [YOUR_PATREON_USERNAME]
open_collective: [YOUR_OPENCOLLECTIVE_USERNAME]
ko_fi: [YOUR_KOFI_USERNAME]
tidelift: [YOUR_TIDELIFT_USERNAME]
community_bridge: [YOUR_COMMUNITYBRIDGE_USERNAME]
liberapay: [YOUR_LIBERAPAY_USERNAME]
issuehunt: [YOUR_ISSUEHUNT_USERNAME]
otechie: [YOUR_OTECHIE_USERNAME]
custom: [YOUR_CUSTOM_URL]